apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-frontend
  template:
    metadata:
      labels:
        app: music-frontend
    spec:
      containers:
        - name: frontend
          image: neferkey/music-frontend:latest
          env:
            - name: VITE_API_BASE_URL
              value: http://music-backend:3000
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: music-frontend
spec:
  type: LoadBalancer
  selector:
    app: music-frontend
  ports:
    - port: 80
      targetPort: 5173
