apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-postgres
  template:
    metadata:
      labels:
        app: music-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: music
            - name: POSTGRES_PASSWORD
              value: music
            - name: POSTGRES_DB
              value: music
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: music-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: music-postgres
spec:
  selector:
    app: music-postgres
  ports:
    - port: 5432
      targetPort: 5432
